# Generated by Django 4.2.5 on 2023-09-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(blank=True, null=True, upload_to='books/cover')),
                ('des', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
